Fix bug where using an invalid xid creates a partial node
This caused errors such as:

bpm stop test
bpm status
Error: open /Users/jonas/.bpm/nodes/test/node.json: no such file or directory

because the node test got created but without node.json